server:
  port: 8761
security:
  basic:
    enabled: true #开启认证
  user:
    name: user
    password: liwen
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
#  server:
#    enable-self-preservation: false  是否开启自我保护
