server:
  port: 8084 #8181
spring:
  application:
    name: microservice-provider-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:liwen@localhost:8761/eureka  #注册 中心已经开启认证
#       defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}