/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_temp_common_jni_MyJniMethod */

#ifndef _Included_com_temp_common_jni_MyJniMethod
#define _Included_com_temp_common_jni_MyJniMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_temp_common_jni_MyJniMethod
 * Method:    add
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_temp_common_jni_MyJniMethod_add
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_temp_common_jni_MyJniMethod
 * Method:    print
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_temp_common_jni_MyJniMethod_print
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_temp_common_jni_MyJniMethod
 * Method:    getadd
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_temp_common_jni_MyJniMethod_getadd
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
