DROP TABLE  IF EXISTS  ACT_ID_USER;
create table ACT_ID_USER
(
  ID_         NVARCHAR2(64) not null,
  REV_        INTEGER,
  FIRST_      NVARCHAR2(255),
  LAST_       NVARCHAR2(255),
  EMAIL_      NVARCHAR2(255),
  PWD_        NVARCHAR2(255),
  PICTURE_ID_ NVARCHAR2(64),
  STATUS_     VARCHAR2(10) default 1,
  STATE_      VARCHAR2(10) default 1,
  PROVINCE    VARCHAR2(32)
);
DROP TABLE  IF EXISTS ACT_ID_GROUP;
create table ACT_ID_GROUP
(
  ID_       NVARCHAR2(64) not null,
  REV_      INTEGER,
  NAME_     NVARCHAR2(255),
  TYPE_     NVARCHAR2(255),
  PID_      NVARCHAR2(64),
  CATEGORY_ NVARCHAR2(64),
  ORDERCODE NUMBER(18),
  ORGCODE   VARCHAR2(200),
  PROVINCE  VARCHAR2(32)
);
DROP TABLE  IF EXISTS ACT_ID_MEMBERSHIP;
create table ACT_ID_MEMBERSHIP
(
  USER_ID_  NVARCHAR2(64) not null,
  GROUP_ID_ NVARCHAR2(64) not null
);




